meiduo/meiduo/apps/areas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # this.host + '/areas/';
    url(r'^areas/$', views.AreasView.as_view())
]

meiduo/meiduo/apps/carts/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    # 添加购物车路由
    # this.host + '/carts/'
    url(r'^carts/$', views.CartsView.as_view(), name='carts'),
    # 购物车的商品全选
    # /carts/selection/
    url(r'^carts/selection/$', views.CartsSelectAllView.as_view()),
    # 购物车的简单展示，在主页、详情等页面展示
    # /carts/simple/
    url(r'^carts/simple/$', views.CartsSimpleView.as_view()),
    ]

meiduo/meiduo/apps/goods/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # 获取商品列表
    # http://www.meiduo.site:8000/list/115/1/
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)/$', views.GoodsListView.as_view()),
    # 获取热销商品数据， 使用vue请求
    # url = this.host + '/hot/' + this.category_id + '/';
    url(r'^hot/(?P<category_id>\d+)/$', views.HotGoodsView.as_view()),
    # 获取商品详情页
    # /detail/(?P<sku_id>\d+)/
    url(r'^detail/(?P<sku_id>\d+)/$', views.DetailGoodView.as_view()),
    # 统计各个第三类商品的浏览量
    #     this.hots + '/visit/' + this.category_id + '/';
    url(r'^visit/(?P<category_id>\d+)/$', views.DetailVisitCount.as_view()),
    # 保存浏览记录
    # url = this.host + '/browse_histories/';
    url(r'^browse_histories/$', views.BrowseHistoriesView.as_view()),
    # 获取评价详情
    # /comments/'+ this.sku_id +'/'
    url(r'^comments/(?P<sku_id>\d+)/$', views.DetailGoodCommentView.as_view()),

]

meiduo/meiduo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import haystack

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    # 后台管理站点
    url(r'^meiduo_admin/', include('meiduo_admin.urls', namespace='meiduo_admin')),
    # 用户应用
    url(r'^', include('users.urls', namespace='users')),
    # 图形验证码、短信验证码应用
    url(r'^', include('verifications.urls', namespace='verifications')),  # 为何没有路由屏蔽:a
    # 主页应用
    url(r'^', include('contents.urls', namespace='contents')),
    # qq 登录应用
    url(r'^', include('oauth.urls', namespace='oauth')),
    # 收货地址的应用
    url(r'^', include('areas.urls', namespace='areas')),
    # 商品列表 （选择三级商品分组， 京东上搜索网页界面的数据也是类似，但是路由不一样，应该是单独做了个应用）
    # http://www.meiduo.site:8000/list/115/1/
    url(r'^', include('goods.urls', namespace='goods')),
    # 购物车应用
    url(r'^', include('carts.urls', namespace='carts')),
    # 订单应用
    url(r'^', include('orders.urls', namespace='orders')),
    # 支付应用
    url(r'^', include('payment.urls', namespace='payment')),

]

meiduo/meiduo/apps/goods/models.py
from django.db import models
from meiduo.utils.models import BaseModel
# Create your models here.



class GoodsCategory(BaseModel):
    """商品类别"""
    name = models.CharField(max_length=10, verbose_name='名称')
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父类别')

    class Meta:
        db_table = 'tb_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'tb_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannel(BaseModel):
    """商品频道"""
    group = models.ForeignKey(GoodsChannelGroup, verbose_name='频道组名')
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='顶级商品类别')
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'tb_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    name = models.CharField(max_length=20, verbose_name='名称')
    logo = models.ImageField(verbose_name='Logo图片')
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'tb_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SPU(BaseModel):
    """商品SPU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name='品牌')
    category1 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别')
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别')
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    desc_detail = models.TextField(default='', verbose_name='详细介绍')
    desc_pack = models.TextField(default='', verbose_name='包装信息')
    desc_service = models.TextField(default='', verbose_name='售后服务')

    class Meta:
        db_table = 'tb_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    caption = models.CharField(max_length=100, verbose_name='副标题')
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, verbose_name='商品')
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='从属类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='市场价')
    stock = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    is_launched = models.BooleanField(default=True, verbose_name='是否上架销售')
    default_image = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='默认图片')

    class Meta:
        db_table = 'tb_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku')
    image = models.ImageField(verbose_name='图片')

    class Meta:
        db_table = 'tb_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)


class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='规格名称')

    class Meta:
        db_table = 'tb_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(BaseModel):
    """规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='规格')
    value = models.CharField(max_length=20, verbose_name='选项值')

    class Meta:
        db_table = 'tb_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku')
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='规格名称')
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格值')

    class Meta:
        db_table = 'tb_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)


class GoodsVisitCount(BaseModel):
    """统计分类商品访问量模型类"""
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='商品分类')
    count = models.IntegerField(verbose_name='访问量', default=0)
    date = models.DateField(auto_now_add=True, verbose_name='统计日期')

    class Meta:
        db_table = 'tb_goods_visit'
        verbose_name = '统计分类商品访问量'
        verbose_name_plural = verbose_name

meiduo/meiduo/apps/areas/views.py
from django.shortcuts import render
from django.views import View
from django import http
from meiduo.utils.response_code import RETCODE
from meiduo.utils.views import LoginRequiredMixin
from .models import Areas
from django.db import DatabaseError
# Create your views here.
from django.core.cache import cache

"""
class AreasView(View):
    # this.host + '/areas/';
    def get(self, request):
        # user = request.user
        area_id = request.GET.get('area_id')
        if area_id is None:
        # 查询所有省级，得到是query_set
            try:
                provinces_qs = Areas.objects.filter(parent__isnull=True)
                # 前段目前是要求一个一个列表province_list
                # 将qs转换成列表
                province_list = []
                for province in provinces_qs:
                    # html中vue渲染指定key名
                    province_dict = {
                        'id': province.id,
                        'name': province.name,
                    }
                    province_list.append(province_dict)
                return http.JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK', 'province_list': province_list})
            except DatabaseError:
                return http.JsonResponse({'code': RETCODE.DBERR, 'errmsg': '无法访问数据'})
        #  城市和行政区共用一个逻辑
        try:
            # 获取指定省/市 的所有的市/区一级
            cities_districts_qs = Areas.objects.filter(parent_id=area_id)
            # parent_area = Areas.objects.get(id=area_id)
            # cities_districts_qs = parent_area.subs.all()

            # 转化成列表
            subs = []
            for cities_districts in cities_districts_qs:
                cities_districts_dict = {
                    'id': cities_districts.id,
                    'name': cities_districts.name,
                }
                subs.append(cities_districts_dict)
            sub_data = {
                        # 'id':parent_area.id,
                        'id': Areas.objects.get(id=area_id).id,
                        'name':Areas.objects.get(id=area_id).name,
                        'subs': subs,
            }
        except DatabaseError as e:
            return http.JsonResponse({'code': RETCODE.DBERR, 'errmsg': '无法访问数据'})    
        return http.JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK', 'sub_data': sub_data})
"""

# 优化数据库访问过于频繁的问题
class AreasView(View):
    # this.host + '/areas/';
    def get(self, request):
        # user = request.user
        area_id = request.GET.get('area_id')
        if area_id is None:
            province_list = cache.get('province_list')
            if province_list is None:
                # 避免数据库异常无法返回数据给前端
                try:
                    # 查询所有省级，得到是query_set
                    provinces_qs = Areas.objects.filter(parent__isnull=True)
                    # 前段目前是要求一个一个列表province_list
                    # 将qs转换成列表
                    province_list = []
                    for province in provinces_qs:
                        # html中vue渲染指定key名
                        province_list.append({'id': province.id, 'name': province.name})
                        cache.set('province_list', province_list, 3600)
                except DatabaseError:
                    return http.JsonResponse({'code': RETCODE.DBERR, 'errmsg': '无法访问数据'})
            return http.JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK', 'province_list': province_list})

        #  城市和行政区共用一个逻辑
        sub_data = cache.get('cities_districts%s' % area_id)
        if not sub_data:
            try:
            # 获取指定省/市 的所有的市/区一级
            # cities_districts_qs = Areas.objects.filter(parent_id=area_id)   # 最直接可取，但是后面需要用到的id、name属性
                parent_area = Areas.objects.get(id=area_id)   # 优化后面的拼接列表
                cities_districts_qs = parent_area.subs.all()
            # 优化读取：
            # 由于不确定要访问的市还是行政区的数据
            # 转化成列表
                subs = []
                for cities_districts in cities_districts_qs:
                    subs.append({'id': cities_districts.id, 'name': cities_districts.name})
                sub_data = {
                            'id': parent_area.id,
                            # 'id': Areas.objects.get(id=area_id).id,    # 前端也没有用到的地方
                            'name': parent_area.name,
                            # 'name':Areas.objects.get(id=area_id).name,
                            'subs': subs,
                }
                cache.set('cities_districts%s' % area_id, sub_data, 3600)
            except DatabaseError as e:
                return http.JsonResponse({'code': RETCODE.DBERR, 'errmsg': '无法访问数据'})
        return http.JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK', 'sub_data': sub_data})

meiduo/meiduo/apps/contents/views.py
from django import http
from django.shortcuts import render
from django.views import View
from .models import Content, ContentCategory
from goods.models import GoodsChannel
from .utils import get_goods_channel

# Create your views here.
class IndexContents(View):
    # 请求首页
    def get(self, request):
        # 获取商品频道分类
        """
        # categories = {}  # 存放所有分组信息
        # # 获取第一层分组, 所有都是一级分类， 但是有分组（手机、运营商、数码）， 和显示的顺序
        # goods_channel_qs = GoodsChannel.objects.all().order_by('group_id', 'sequence')
        # for goods_channel in goods_channel_qs:
        #     group_id = goods_channel.group_id
        #     # 判断当前的组号在字典中是否存在
        #     if group_id not in categories:
        #         # 不存在,包装一个当前组的准备数据()相当于商品频道的每一行
        #         categories[group_id] = {'channels': [], 'sub_cats': []}  # chanel 是商品中的手机
        #     # 获取一级类别数据  得到1,2,3...37  又对象转1d
        #     cat1 = goods_channel.category
        #     # 将频道中的url绑定给一级类型对象  # 跳转到一类的东西的广告界面:www.jiaju.jd.com
        #     cat1.url = goods_channel.url
        #     # 将id加入到字典的chanels字段中
        #     categories[group_id]['channels'].append(cat1)
        #     # 获取当前一组下面的所有二级数据， 隐士外建查找
        #     cat2_qs = cat1.subs.all()
        #     # 遍历二级数据查询集
        #     for cat2 in cat2_qs:
        #         cat3_qs = cat2.subs.all()  # 获取当前二级下面的所有三级 得到三级查询集
        #         cat2.sub_cats = cat3_qs  # 把二级下面的所有三级绑定给cat2对象的sub_cats属性
        #         categories[group_id]['sub_cats'].append(cat2)
                categories = get_goods_channel()
        """
        categories = get_goods_channel()
        # # 获取广告数据
        # 具体的广告
        contents = {}
        # 类别
        content_category = ContentCategory.objects.all()
        for category in content_category:
            # content表建立时外建时没有给contentcategory 的隐士外建指定别名，故
            # 返回的广告数据类型:{类别： 该类的所有具体广告对象的qs,
            contents[category.key] = category.content_set.filter(status=True).order_by('sequence')
        context = {
            # 此处要返回啥， 需要看前端怎么渲染
            'categories': categories,
            'contents': contents
        }
        return render(request, 'index.html', context)

meiduo/meiduo/apps/meiduo_admin/views/admins_views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import ListAPIView
from meiduo_admin.serializers.admins_serializer import *
from meiduo_admin.utils.user_pages import MyUserPagination
from rest_framework.response import Response


class AdminUserViewSet(ModelViewSet):
    queryset = User.objects.filter(is_staff=True)
    serializer_class = AdminUserSerializer
    pagination_class = MyUserPagination

    # 为了解决数据库是telephone，前端是mobile， 重写展示的方法
    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            admin_user_list = serializer.data
            for one_user_dict in admin_user_list:
                one_user_dict['mobile'] = one_user_dict.pop('telephone')
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)
        admin_user_list = serializer.data
        for one_user_dict in admin_user_list:
            one_user_dict['mobile'] = one_user_dict.pop('telephone')
        return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        request.data['telephone'] = request.data.pop('mobile')
        return super().create(request, *args, **kwargs)

    def update(self, request, *args, **kwargs):
        request.data['telephone'] = request.data.pop('mobile')
        return super().update(request, *args, **kwargs)


class GroupSimpleView(ListAPIView):
    queryset = Group.objects.all()
    serializer_class = GroupSimpleSerializer

meiduo/meiduo/apps/meiduo_admin/views/brand_views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import ListAPIView
from django.db.models import Q
from meiduo_admin.serializers.brand_serializer import *
from meiduo_admin.utils.user_pages import MyUserPagination


class BrandViewSet(ModelViewSet):
    queryset = Brand.objects.all()
    serializer_class = BrandModelSerializer
    pagination_class = MyUserPagination

meiduo/meiduo/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>美多商城-登录</title>
    <link rel="stylesheet" type="text/css" href="../static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../static/css/main.css">
    <script type="text/javascript" src="../static/js/host.js"></script>
    <script type="text/javascript" src="../static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="../static/js/axios-0.18.0.min.js"></script>

</head>
<body>
<div id="app" v-cloak>
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo"><img src="../static/images/logo02.png"></a>
    </div>
    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">商品美 · 种类多 · 欢迎光临</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <a href="javascript:;" class="cur">账户登录</a>
                </div>
                <div class="form_con">
                    <div class="form_input cur">
                        <form method="post" class="login" @submit="on_submit">
                            {{ csrf_input }}
                            <input type="text" name="username" v-model="username" @blur="check_username"
                                   class="name_input" placeholder="请输入用户">
                            <div class="user_error" v-show="error_username">[[ error_username_message ]]</div>

                            <input type="password" name="password" v-model="password" @blur="check_pwd" class="pass_input"
                                   placeholder="请输入密码">

                            <div class="pwd_error" v-show="error_password">[[ error_password_message ]]</div>
                            <div class="more_input clearfix">
                                <input type="checkbox" name="remembered" v-model="remembered">
                                <label>记住登录</label>
                                <a href="/find_password">忘记密码</a>
                            </div>
                            <input type="submit" value="登 录" class="input_submit">
                            {% if loginerror %}
                                <span class="error_tip2">{{ loginerror }}</span>
                            {% endif %}
                        </form>
                    </div>
                </div>
                <div class="third_party">
                    <a href="javascript:;" class="qq_login" @click="qq_login">QQ</a>
                    <a @click="weibo_login" class="weixin_login" >微信</a>
                    <a href="#" class="weibo_login" @click="weibo_login">微博</a>
                    <a href="/register/" class="register_btn">立即注册</a>
                </div>

            </div>
        </div>
    </div>

    <div class="footer no-mp">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
    <script type="text/javascript" src="../static/js/common.js"></script>
    <script type="text/javascript" src="../static/js/login.js"></script>
</body>
</html>

meiduo/meiduo/templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>美多商城-我的订单</title>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.pagination.css">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/host.js"></script>
    <script type="text/javascript" src="/static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="/static/js/axios-0.18.0.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
</head>
<body>
<div id="app" v-cloak>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到美多商城!</div>
            <div class="fr">
                <div class="login_btn fl" v-if="username">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="/logout/" class="quit">退出</a>
                </div>
                <div class="login_btn fl" v-else>
                    <a href="/login/">登录</a>
                    <span>|</span>
                    <a href="/register/">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="/info/">用户中心</a>
                    <span>|</span>
                    <a href="/carts/">我的购物车</a>
                    <span>|</span>
                    <a href="/orders/info/1/">我的订单</a>
                </div>
            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="search_wrap fl">
            <form method="get" action="/search/" class="search_con">
                <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
            <ul class="search_suggest fl">
                <li><a href="#">索尼微单</a></li>
                <li><a href="#">优惠15元</a></li>
                <li><a href="#">美妆个护</a></li>
                <li><a href="#">买2免1</a></li>
            </ul>
        </div>
    </div>

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="/info/">· 个人信息</a></li>
                <li><a href="/orders/info/1/" class="active">· 全部订单</a></li>
                <li><a href="/addresses/">· 收货地址</a></li>
                <li><a href="/password/">· 修改密码</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in page_orders %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_time.strftime('%Y-%m-%d %H:%M:%S') }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                </ul>
                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for sku in order.sku_list %}
                                <ul class="order_goods_list clearfix">

                                    <li class="col01"><a @click="sku_detail"><img src="{{ sku.default_image.url }}" ></a></li>
                                    <li class="col02"><span>{{ sku.name }}</span><em>{{ sku.price }}元</em></li>
                                    <li class="col03">{{ sku.count }}</li>
                                    <li class="col04">{{ sku.amount }}元</li>
                                    <input v-model="sku_id" type="hidden" value="{{ sku.sku_id }}">
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_amount }}元<br>含运费：{{ order.freight }}元</td>
                        <td width="15%">{{ order.pay_method_name }}</td>
                        <td width="15%">
                            <a @click="oper_btn_click('{{ order.order_id }}', {{ order.status }})"
                               class="oper_btn">{{ order.status_name }}</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}
            <div class="pagenation">
                <div id="pagination" class="page"></div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
<script type="text/javascript" src="/static/js/jquery.pagination.min.js"></script>
<script type="text/javascript" src="/static/js/common.js"></script>
<script type="text/javascript" src="/static/js/base.js"></script>
<script type="text/javascript" src="/static/js/user_center_order.js"></script>
<script>
    $(function () {
        $('#pagination').pagination({
            currentPage: {{ page_num }},
            totalPage: {{ total_page }},
            callback: function (current) {
                location.href = '/orders/info/' + current + '/';
            }
        })
    });
</script>

</body>
</html>